# Generated by Django 5.2.4 on 2025-07-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrop', '0003_remove_produto_categoria_remove_produto_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
